# Generated by Django 5.1.2 on 2024-11-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=255)),
                ('car_name', models.CharField(max_length=255)),
                ('price_per_day', models.IntegerField()),
                ('brand_name', models.CharField(max_length=255)),
                ('number_of_seats', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('horse_power', models.IntegerField()),
                ('engine_capacity', models.FloatField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid&Petrol // Hybrid&Diesel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api.car')),
            ],
        ),
    ]
