# Generated by Django 5.1.3 on 2024-12-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_favorite_cars_userfavoritecar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfavoritecar',
            constraint=models.UniqueConstraint(fields=('user', 'car'), name='unique_favorite'),
        ),
    ]
