# Generated by Django 5.1.3 on 2024-12-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userchart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChart',
            new_name='UserCart',
        ),
        migrations.RemoveConstraint(
            model_name='usercart',
            name='chart',
        ),
        migrations.AddConstraint(
            model_name='usercart',
            constraint=models.UniqueConstraint(fields=('user', 'car'), name='cart'),
        ),
    ]
